vercel/react-tweet

- packages/next-tweet/readme.md
The component prop is `id`, not `params.tweet`.
> Fix documentation of component props in readme.md

- packages/next-tweet/src/tweet-media-video.module.css
- packages/next-tweet/src/tweet-media-video.tsx
Using `role="button"` without the accompanying event handlers that a native `button` provides creates an experience that is not accessible to keyboard users. [MDN - ARIA: button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#sect1)
Unless there is a specific reason not to, this should just be a `button`. This changes that, and adds  `:focus-visible` css for additional visual indication.
> Make video play button keyboard accessible

- packages/next-tweet/src/skeleton.module.css
As an accessibility enhancement, to better serve users who may have set their OS to reduce the amount of motion on screen, we should check for that and disable the Skeleton's animation.
> Honor prefers-reduce-motion when animating the skeleton

- packages/next-tweet/src/tweet-info.tsx
This `<a>` contains only an `<svg>` and no accessible text, which makes it unusable to screen readers. This adds text via an `aria-label` attribute.
In lieu of the `aria-` attribute, I would normally resolve this kind of thing with an `sr-only` or `visually-hidden` type of utility class and related CSS to allow the content inside the `<a>` to exist, but I'm not seeing any existing pattern/class like that in this project, so the `aria-label` should suffice.
> Add accessible text to icon only link in `TweetInfo`

- packages/next-tweet/src/tweet-body.tsx
Fixes #29 
Most of the details are over on the issue (#29), but the gist is that the API responds with encoded HTML entities. In order to properly render those, we need to use `dangerouslySetInnerHTML` on the containing `<span>`.
> Decode HTML entities in body

- apps/test-app/app/light/[tweet]/page.tsx
- apps/test-app/app/light/mdx/page.tsx
- apps/test-app/app/light/suspense/[tweet]/page.tsx
- packages/next-tweet/readme.md
- packages/next-tweet/src/tweet.tsx
This commit enhances the developer experience since `NextTweet` component no longer needs a `ts-ignore` (or similar) comment, as the component itself is no longer `async`.
Functionally it should still work normally. I have done some manual tests on all `test-app` pages, but you might want to test it too.
Although if this PR is merged, it will (I think) break the build for anyone using `ts-expect-error` instead of `ts-ignore`. But we are in v0.x.x here so I think a minor version bump is fine...
> Make ts-ignore comments no longer necessary

- packages/next-tweet/src/tweet-media-video.tsx
Currently, when navigating a tweet that contains a video, the tab order and focus management after selecting play is a bit cumbersome. 
- `<video>` elements are keyboard focusable elements, but since we have `controls` attr set to false when the play button is visible, a user cannot actually control the video when focusing it. There is also no visual indication that the video is focused, so it presents as an empty slot between the tweet header and the play button.
- after focusing through this empty slot with a tab press, the play button is focused. if selected with enter/space, the button is removed and the video is played, but focus is not managed. user has to press tab again to focus the video to control it (pause/play/volume/etc)
- `<video>` element itself is taken out of the tab …
> Better focus manangement in `TweetMediaVideo`

- packages/next-tweet/src/api/types/entities.ts
- packages/next-tweet/src/tweet-body.tsx
- packages/next-tweet/src/utils.ts
Noticed it was not linking stock symbols in the tweet body. This links them up to a search query URL to match Twitter functionality.
> Add support for stock symbols in tweet body

- packages/next-tweet/src/api/types/media.ts
- packages/next-tweet/src/tweet-media.tsx
Twitter allows users to add `alt` text to their images when adding them to a tweet. The API also exposes this to us for photo media types. We should use that user-provided alt test as descriptive text on the `img` if provided.
Additionally, since the `<Image />` is the only descendant of the containing `<a>`, an `aria-label` on the anchor is duplicative. A screen reader will use the `img` alt tag as the anchor text. Removing the `aria-label` attribute will keep a screen reader from reading out the same text twice in row.
[Example tweet](https://twitter.com/CaseyNewton/status/1632849093897891840) where alt text is provided
> Use provided image `alt` text if user added one

- packages/react-tweet/src/embedded-tweet.tsx
The setup to use a custom component for `MediaImg` was there, but was never actually passed through to the `<TweetMedia />` component, so was not working.
This resolves that issue by providing the prop to `<TweetMedia />`
> Use custom MediaImg component if provided

- packages/react-tweet/src/api/get-tweet.ts
I believe the incorrect cached status codes this was added to fix was addressed here: https://github.com/vercel/next.js/pull/47096
Closes https://github.com/vercel-labs/react-tweet/issues/66
> get-tweet: remove now-unnecessary `no-cache`

- packages/react-tweet/src/tweet-replies.tsx
- packages/react-tweet/src/utils.ts
There was a grammatical error in the way that the `TweetReplies` component would output text for the replies link, where it always output the pluralized version of "replies instead of using "reply" where appropriate.
For example, it would output "Read 1 replies" when it should be "Read 1 reply".
This change builds the link text looking for each possible grammatical case:
- `0` -> `Read more on Twitter`
- `1` -> `Read 1 reply`
- `2 (or more)` -> `Read 2 replies`
> Fix link text grammar in TweetReplies component

- apps/create-react-app/src/app.module.css
- apps/vite-app/src/layout.module.css
Two of the demo apps had layouts that were not allowing the tweet to shrink for small window sizes.
This change brings those two apps into sync with the styles from `apps/next-app` (which handled it well.)
Before:
After:
> Responsive layout in demo apps

- packages/react-tweet/src/twitter-theme/tweet-media.module.css
- packages/react-tweet/src/twitter-theme/tweet-media.tsx
The changes introduced in #99 inadvertently broke the media layouts when there is more than one image present (reported in #101).
The changes presented here will keep with the spirit of making the base theme match Twitter as closely as possible, while also supporting a grid of multiple images.
> Fix regression in media layout with multiple images

- packages/react-tweet/src/twitter-theme/tweet-header.module.css
Hello maintainers,
The margin-left property was changed to margin-inline-start to have proper position of the Twitter icon on websites with dir attribute set to rtl direction. This change resolves the visual inconsistencies. The modification has been tested and does not impact left-to-right websites.
> fix position twitter icon for dir=rtl

- apps/next-app/app/light/[tweet]/tweet-components.tsx
- apps/site/pages/next.mdx
- apps/site/pages/twitter-theme/api-reference.mdx
Hello! I thoroughly enjoyed exploring the library. While experimenting with it, I observed that the `TweetComponents` mentioned in the documentation have been marked as deprecated. So, I've created this pull request to replace the outdated interface name with the accurate one, `TwitterComponents`.
> Replace deprecated interface name for Tweet components prop

- .changeset/honest-rabbits-swim.md
- .changeset/stupid-nails-eat.md
- packages/react-tweet/src/api/get-tweet.ts
Twitter API calls in https://publish.twitter.com/ include a `token` that I was not including before. I've been noticing that APi calls start returning an empty object `{}` after a while if that token is not added so I looked into their minified code to know how that token is calculated and added that here.
> Add missing token to api calls to Twitter's CDN

- packages/react-tweet/src/api/types/user.ts
I'm not sure if this library should also handle the _styling_ of hexagon avatars, but I think this should be included in the type definitions for package users who are extending components on their own.
> Add Hexagon as valid profile_image_shape

- packages/react-tweet/src/twitter-theme/tweet-link.tsx
- Content from embedded tweets is now follow, but should be ugc or nofollow
> Update tweet-link.tsx - make it nofollow

- packages/react-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-body.tsx
- packages/react-tweet/src/twitter-theme/tweet-body.tsx
Tweets can be written in various languages. Language metadata is essential for browsers to correctly render multilingual texts because the different language uses different shapes of glyphs for the same Unicode codepoints, and the browsers must select fonts based on the intended language[^1].
Twitter API infers the primary language of each tweet, and this patch sets the `lang` attribute to the inferred language for the tweet bodies. `dir="auto"` is also necessary for proper rendering of texts in the right-to-left languages, such as Arabic, Hebrew, and Persian.
---
This test tweet in Japanese contains several Han characters which present regional variation (See [^1] for details): https://twitter.com/k_hanazuki/status/1803451841684111591
- Without the patch, incorrect glyphs (Chinese …
> Set `lang` and `dir` attributes on tweet bodies

- package.json
- packages/react-tweet/src/twitter-theme/tweet-actions-copy.tsx
- packages/react-tweet/src/twitter-theme/tweet-info.tsx
- packages/react-tweet/src/utils.ts
- pnpm-lock.yaml
* `twitter.com` now redirects to `x.com`, so I updated links that `react-tweet` generates accordingly.
* Removed some unused state from the copy link button. Not sure why it was there, but it didn't seem to be doing anything.
* Updated `pnpm` to v9.
> Update links to x.com

- packages/react-tweet/package.json
- packages/react-tweet/src/utils.ts
Hi!
I'd like to use api/util functions without React dependency in my non-react project(like https://github.com/ryoppippi/sveltweet)
So I added `utils` export path to package.json
> export utils
